apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataframe-playground-flask-server
  labels:
    app: dataframe-playground-flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataframe-playground-flask-server
  template:
    metadata:
      labels:
        app: dataframe-playground-flask-server
    spec:
      containers:
      - name: dataframe-playground-flask-server
        image: {{image_name_placeholder}}
        ports:
        - containerPort: 80
        env:
        - name: mongocredential
          value: mongo_connection_placeholder
        - name: CHART_STUDIO_API_KEY
          value: chart_studio_key_placeholder
      imagePullSecrets:
      - name: githubdockerregistry
